version: '3.7'

services:

  ## ** services **
  srv-users:
    build:
      dockerfile: docker/backend.Dockerfile
      context: .
    command: sh -c "/wait && cd packages/srv-users && npm run migrate:up && node dist/main.js"
    ports:
      - '${SRV_USER_HTTP_PORT}:${SRV_USER_HTTP_PORT}'
    depends_on:
      - postgres
    networks:
      - popug
    labels:
      application: popug
    volumes:
      - ./keys:/app/keys
      - ./logs:/app/logs
    environment:
      SRV_USER_JWT_PUBLIC_KEY: ${SRV_USER_JWT_PUBLIC_KEY:-/app/keys/id_rsa_pub.pem}
      SRV_USER_JWT_PRIVATE_KEY: ${SRV_USER_JWT_PRIVATE_KEY:-/app/keys/id_rsa_priv.pem}
      SRV_USER_DATABASE_URL: ${SRV_USER_DATABASE_URL:-postgresql://srv_users_usr:asdvcw23fawef@postgres:5432/srv_users_db}
      SRV_USER_AMQP_URI: ${SRV_USER_AMQP_URI:-amqp://srv_users_login:asdvcw23fawef@rabbit-mq:5672/}
      SRV_USER_LOG_DIR: ${SRV_USER_LOG_DIR:-/app/logs/srv-users}
      SRV_USER_LOGGER_DEBUG: ${SRV_USER_LOGGER_DEBUG:-on}
      SRV_USER_IS_PRODUCT: ${SRV_USER_IS_PRODUCT:-false}
      SRV_USER_SENDGRID_API_KEY: ${SRV_USER_SENDGRID_API_KEY:-aaaaaa}
      SRV_USER_EMAILS_IS_ACTIVE: ${SRV_USER_EMAILS_IS_ACTIVE:-false}
      SRV_USER_EMAIL_NOTIFICATION: ${SRV_USER_EMAIL_NOTIFICATION:-info@popug.app}
      SRV_USER_DEVELOP_PUBLIC_URL: ${SRV_USER_DEVELOP_PUBLIC_URL:-}
      SRV_USER_APP_VERSION: ${SRV_USER_APP_VERSION:-0.1.0}
      SRV_USER_HTTP_PORT: ${SRV_USER_HTTP_PORT:-3700}
      SRV_USER_HTTP_JSON_LIMIT: ${SRV_USER_HTTP_JSON_LIMIT:-10mb}

  srv-tasks:
    build:
      dockerfile: docker/backend.Dockerfile
      context: .
    command: sh -c "/wait && cd packages/srv-tasks && npm run migration:up && node dist/main.js"
    ports:
      - '${SRV_VEHICLES_HTTP_PORT}:${SRV_VEHICLES_HTTP_PORT}'
    depends_on:
      - postgres
    networks:
      - popug
    labels:
      application: popug
    volumes:
      - ./keys:/app/keys
      - ./logs:/app/logs
    environment:
      SRV_VEHICLES_JWT_PUBLIC_KEY: ${SRV_VEHICLES_JWT_PUBLIC_KEY:-/app/keys/id_rsa_pub.pem}
      SRV_VEHICLES_POSTGRES_CONNECT_URL: ${SRV_VEHICLES_POSTGRES_CONNECT_URL:-postgresql://srv_tasks_usr:asdvcw23fawef@postgres:5432/srv_tasks_db}
      SRV_VEHICLES_AMQP_URI: ${SRV_VEHICLES_AMQP_URI:-amqp://srv_tasks_usr:asdvcw23fawef@rabbit-mq:5672/}
      SRV_VEHICLES_LOG_DIR: ${SRV_VEHICLES_LOG_DIR:-/app/logs/srv-tasks}
      SRV_VEHICLES_LOGGER_DEBUG: ${SRV_VEHICLES_LOGGER_DEBUG:-on}
      SRV_VEHICLES_IS_PRODUCT: ${SRV_VEHICLES_IS_PRODUCT:-false}
      SRV_VEHICLES_HTTP_PORT: ${SRV_VEHICLES_HTTP_PORT:-3702}
      SRV_VEHICLES_HTTP_JSON_LIMIT: ${SRV_VEHICLES_HTTP_JSON_LIMIT:-10mb}
      SRV_VEHICLES_APP_VERSION: ${SRV_VEHICLES_APP_VERSION:-0.1.0}
      SRV_VEHICLES_DEVELOP_PUBLIC_URL: ${SRV_VEHICLES_DEVELOP_PUBLIC_URL:-https://api.dev.popug.systems/tasks/}

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
#      POSTGRES_DB: po
      PGDATA: /data/postgres

    ulimits:
      nofile:
        hard: 262144
        soft: 262144
    labels:
      application: popug

    volumes:
      - postgres-data:/data/postgres
      - ./docker/postgres-entrypoint-initdb:/docker-entrypoint-initdb.d

    ports:
      - ${POSTGRES_PORT:-8432}:5432
    networks:
      - popug
    restart: unless-stopped

#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4:4.22
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-123456}
#      DB_HOST: postgres
#    volumes:
#      - pgadmin:/root/.pgadmin
#    labels:
#      application: popug
#    ports:
#      - "${PGADMIN_PORT:-8450}:80"
#    networks:
#      - popug
#    restart: unless-stopped

  rabbit-mq:
    container_name: rabbit-mq
    build: docker/rabbit-mq
    hostname: rabbit-mq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-radmin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-123456}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST:-rabbitMq}
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE:-SWQOKODSQALRPCLNMEQG}
      RABBITMQ_LOG_BASE : /var/log/rabbitmq
      RABBITMQ_MNESIA_BASE: /var/lib/rabbitmq
      RABBITMQ_SCHEMA_DIR: /var/lib/rabbitmq
    volumes:
      - rabbit-data:/var/lib/rabbitmq
      - rabbit-logs:/var/log/rabbitmq
    ports:
      - "4369:4369"
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
      - "35197:35197"
    networks:
      - popug
#  nginx:
#    container_name: popug-nginx
#    image: nginx:1.15-alpine
#    hostname: crt-nginx
#    restart: always
#    #    environment:
#    networks:
#      - popug
#    volumes:
#      - nginx-conf:/etc/nginx/conf.d
#      - nginx-sites:/var/www/sites
#      - nginx-logs:/var/log
#      - letsencrypt:/etc/letsencrypt
#      - certbot:/var/www/certbot
#    ports:
#      - "80:80"
#      - "443:443"
#    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
#    labels:
#      application: popug
#  certbot:
#    image: certbot/certbot
#    volumes:
#      - letsencrypt:/etc/letsencrypt
#      - certbot:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
#    labels:
#      application: popug

volumes:
  rabbit-data:
  rabbit-logs:
  apps-logs:
  postgres-data:
  postgres-logs:
  pgadmin:
#  certbot:
#  letsencrypt:
#  nginx-sites:
#  nginx-conf:
#  nginx-logs:



networks:
  popug:
    name: popug
    driver: bridge

